services:
  - type: web
    name: levisty
    env: node
    plan: free
    buildCommand: |
      npm install
      pip install --upgrade pip
      pip install pytube yt-dlp
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: levisty
          property: port
    autoDeploy: true
    branch: main
    rootDir: .
    
    # Persistent storage for Python virtual environment
    disk:
      name: python-venv
      mountPath: /opt/render/project/src/venv
      sizeGB: 1 